# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/webdevelopment_doc',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/webdevelopment_doc',
                'lib_path': 'webdevelopment_doc'},
  'syms': {'webdevelopment_doc.core': {'webdevelopment_doc.core.foo': ('core.html#foo', 'webdevelopment_doc/core.py')}}}
